apiVersion: v1
kind: Secret
metadata:
  name: zabbix-secrets
  namespace: default
type: Opaque
stringData:
  ZABBIX_URL: "http://your-zabbix-server/zabbix/api_jsonrpc.php"
  ZABBIX_USER: "api_provisioning"
  ZABBIX_PASS: "your_secure_password"
